# Generated by Django 6.0 on 2026-01-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_longtitude',
            new_name='delivery_longitude',
        ),
    ]
